Repository Morfusee/Firestore-ERD-Plus, pull requests merged in 2025-01, with the labels that each got.

#10 FEAT: Create Docker Image Workflow
  .github/workflows/docker-image.yml
Labels: enhancement

#15 FIX: Errors in HistoryRoutes, History and Project Controllers, and History and Project Models
  server/controllers/historyControllers.ts
  server/models/historyModel.ts
  server/models/projectModel.ts
  server/routes/historyRoutes.ts
Labels: enhancement, fix

#16 Fix: Ensure proper flow control in API handlers and middleware
  server/controllers/userController.ts
  server/middleware/userValidator.ts
Labels: fix

#17 FEAT (Users): Implemented Deletion of User
  server/controllers/userController.ts
  server/models/userModel.ts
  server/package-lock.json
  server/routes/projectRoutes.ts
  server/routes/userRoutes.ts
Labels: enhancement

#18 FEAT (Members): Implemented CRUD and routes
  server/app.ts
  server/controllers/memberControllers.ts
  server/errors/ConflictError.ts
  server/errors/HTTPError.ts
  server/errors/NotFoundError.ts
  server/errors/ValidationError.ts
  server/middleware/errorMiddleware.ts
  server/middleware/memberValidator.ts
  server/models/memberModel.ts
  server/models/projectModel.ts
  server/models/userModel.ts
  server/routes/memberRoutes.ts
  server/types/memberTypes.ts
Labels: enhancement

#20 FIX: Quick fix to adding share project to user
  server/controllers/memberControllers.ts
Labels: fix

#22 FEAT: Implemented Endpoint for Fetching of Emojis from 3rd Party and on the Frontend
  .env.template
  .gitignore
  server/app.ts
  server/controllers/emojiControllers.ts
  server/routes/emojiRoutes.ts
  server/types/emojiTypes.ts
  src/App.tsx
  src/components/AsyncEmojiPicker.tsx
  src/components/TopLeftBar.tsx
  src/components/modals/DeleteModal.tsx
  src/components/modals/DrawerModal.tsx
  src/types/EmojiData.ts
  src/utils/useEmojiData.tsx
  src/utils/useTheme.tsx
Labels: enhancement

#23 FEAT (Drawer): Implemented Creating and Fetching of Projects
  server/app.ts
  server/controllers/projectController.ts
  server/middleware/responseStatusMiddleware.ts
  server/middleware/successMiddleware.ts
  server/models/projectModel.ts
  server/routes/projectRoutes.ts
  server/success/SuccessResponse.ts
  server/types/projectTypes.ts
  src/components/TopLeftBar.tsx
  src/components/modals/DrawerModal.tsx
  src/data/api/projectsApi.ts
  src/data/db/AppDB.ts
  src/data/db/Project.ts
  src/data/repo/useDataInitializer.ts
  src/data/repo/useProjectRepo.ts
  src/store/useProjectStore.ts
  src/types/ProjectTypes.ts
Labels: enhancement
