Repository Morfusee/Firestore-ERD-Plus, pull requests merged in 2025-02, with the labels that each got.

#27 feat: enhance settings management and fix user reference in controllers
  server/controllers/settingsControllers.ts
  server/models/historyModel.ts
  server/models/projectModel.ts
  server/models/settingsModel.ts
  server/models/userModel.ts
  server/utils/mongooseTransformPlugin.ts
Labels: enhancement, fix

#28 feat: Implement cascade deletion, user-owned projects, and settings management enhancements
  server/controllers/settingsControllers.ts
  server/controllers/userController.ts
  server/models/historyModel.ts
  server/models/projectModel.ts
  server/models/settingsModel.ts
  server/models/userModel.ts
  server/routes/userRoutes.ts
  server/utils/mongooseTransformPlugin.ts
Labels: enhancement, fix

#31 feat: Initialize Firebase & Implement Authentication
  .gitignore
  server/app.ts
  server/config/firebase.ts
  server/controllers/authController.ts
  server/middleware/validators/authValidator.ts
  server/package.json
  server/pnpm-lock.yaml
  server/routes/authRoutes.ts
  server/routes/projectRoutes.ts
  server/routes/settingsRoutes.ts
  server/routes/userRoutes.ts
  server/success/SuccessResponse.ts
Labels: enhancement

#32 hotfix: fixed importing of service account key
  server/.dockerignore
  server/compose-dev.yml
  server/config/firebase.ts
  server/package-lock.json
  server/pnpm-lock.yaml
Labels: fix

#33 feat: Initialize Firebase & Implement Authentication
  .gitignore
  server/.dockerignore
  server/app.ts
  server/compose-dev.yml
  server/compose-prod.yml
  server/config/firebase.ts
  server/controllers/authController.ts
  server/middleware/validators/authValidator.ts
  server/package-lock.json
  server/package.json
  server/routes/authRoutes.ts
  server/routes/projectRoutes.ts
  server/routes/settingsRoutes.ts
  server/routes/userRoutes.ts
  server/success/SuccessResponse.ts
Labels: enhancement, fix

#34 Feature Enhancements and Comprehensive Code Cleanup
  package-lock.json
  package.json
  server/controllers/authController.ts
  server/middleware/validators/authValidator.ts
  server/routes/authRoutes.ts
  server/types/authTypes.ts
  src/App.tsx
  src/components/TopRightBar.tsx
  src/components/modals/DownloadModal.tsx
  src/data/api/authApi.ts
  src/data/api/projectsApi.ts
  src/data/api/userApi.ts
  src/data/repo/useDataInitializer.ts
  src/data/repo/useDownloadRepo.ts
  src/data/repo/useEditorRepo.ts
  src/data/repo/useUserRepo.ts
  src/pages/FirestoreERD.tsx
  src/pages/login/index.tsx
  src/pages/register/index.tsx
  src/routes/ProtectedRoute.tsx
  src/types/APITypes.ts
  src/types/DownloadModalTypes.ts
  src/utils/useAuth.tsx
  vite.config.ts
Labels: enhancement, fix

#37 Add Image Cropping Feature and Enhance Profile Management
  package-lock.json
  package.json
  src/App.tsx
  src/components/modals/ImageCropperModal.tsx
  src/components/modals/ManageAccountModal.tsx
  src/css/index.css
  src/data/repo/useUserRepo.ts
  src/store/useUserStore.ts
Labels: enhancement

#38 Implement Form Validation and Refactor Codebase
  src/App.tsx
  src/components/SampleComponent.tsx
  src/components/modals/DownloadModal.tsx
  src/components/modals/DrawerModal.tsx
  src/components/modals/SettingsModal.tsx
  src/components/ui/AsyncEmojiPicker.tsx
  src/components/ui/ConditionalHoverCard.tsx
  src/components/ui/EmojiPicker.tsx
  src/components/ui/TextSelect.tsx
  src/components/utils/DeferredRender.tsx
  src/components/utils/Virtualizer.tsx
  src/data/api/projectsApi.ts
  src/data/repo/useUserRepo.ts
  src/hooks/useAuth.tsx
  src/hooks/useEmojiData.tsx
  src/hooks/useGlobalHotkeys.tsx
  src/hooks/useIsDarkMode.tsx
  src/hooks/useIsTruncated.tsx
  src/hooks/useProjectIcon.tsx
  src/hooks/useTheme.tsx
  src/layouts/BottomMiddleBar.tsx
  src/layouts/TopLeftBar.tsx
  src/layouts/TopMiddleBar.tsx
  src/layouts/TopRightBar.tsx
  src/pages/FirestoreERD.tsx
  src/pages/editor/index.tsx
  src/pages/editor/nodes/NoteNode.tsx
  src/pages/editor/nodes/TableNode.tsx
  src/pages/login/index.tsx
  src/pages/register/index.tsx
  src/routes/ProtectedRoute.tsx
  src/types/APITypes.ts
  src/utils/errorHelpers.ts
  src/utils/firebaseErrorMessages.ts
Labels: enhancement, fix

#39 feat: improved login and signing up mechanisms to protect auth provider
  server/config/firebase.ts
  server/controllers/authController.ts
  src/pages/login/index.tsx
  src/pages/register/index.tsx
  src/utils/errorHelpers.ts
Labels: enhancement, fix

#41 fix: moved server packages to server dir
  package-lock.json
  package.json
  server/compose-dev.yml
  server/compose-prod.yml
  server/package-lock.json
  server/package.json
Labels: enhancement, fix

#42 feat: add image compression middleware using sharp
  package-lock.json
  package.json
  server/middleware/compressImageMiddleware.ts
  server/package-lock.json
  server/package.json
  server/routes/userRoutes.ts
Labels: enhancement

#43 Enhancements and Bug Fixes for Authentication, Emoji Management, and Profile Handling
  server/controllers/authController.ts
  server/controllers/emojiControllers.ts
  server/middleware/validators/authValidator.ts
  server/utils/getFirebaseAuthErrorMessage.ts
  src/components/modals/ImageCropperModal.tsx
  src/components/modals/ManageAccountModal.tsx
  src/components/ui/ProfileAvatar.tsx
  src/data/api/emojiApi.ts
  src/data/api/userApi.ts
  src/data/db/AppDB.ts
  src/data/repo/useEmojiRepo.ts
  src/data/repo/useUserRepo.ts
  src/hooks/useEmojiData.tsx
  src/layouts/TopRightBar.tsx
  src/store/useUserStore.ts
  src/types/APITypes.ts
Labels: enhancement, fix

#44 FEAT: Implemented Project Sharing Displaying and Add/Remove Project Members
  server/controllers/memberControllers.ts
  server/controllers/projectController.ts
  server/middleware/validators/memberValidator.ts
  server/models/projectModel.ts
  server/routes/memberRoutes.ts
  src/components/modals/ShareModal.tsx
  src/components/ui/ProfileAvatar.tsx
  src/data/api/membersApi.ts
  src/data/repo/useDataInitializer.ts
  src/data/repo/useMemberRepo.ts
  src/data/repo/useProjectRepo.ts
  src/store/useMemberStore.ts
  src/store/useProjectStore.ts
  src/types/APITypes.ts
  src/types/ProjectTypes.ts
Labels: enhancement, fix

#46 Enhance Role-Based Access Control in Share Modal
  server/types/memberTypes.ts
  src/components/modals/ShareModal.tsx
  src/data/api/membersApi.ts
Labels: enhancement
